### PR TITLE
Version Bump to 0.7.0

### PR DESCRIPTION
**Pull request by nikicc**
Update recipe for 0.7.0 version.

Due to some problems with downloading miniconda on AppVeyor (pelson/Obvious-CI#67) feedstock was upgraded with `conda-smithy regenerate`.

This should also add py36 builds.

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Did you regenerate with the latest version of conda smithy? It in general looks fine, but might want to try again to see about covering `py36`.

**Review by pmlandwehr — APPROVED** [review]

**Comment by nikicc** [comment]
@pmlandwehr I regenerated with conda-smithy 2.0.1. I tried it one more time and no luck — py36 is still not there. Will try to investigate further.

**Comment by nikicc** [comment]
@pmlandwehr supposedly this will start building for py36 when all the dependencies will be build for py36. Since only `oauthlib` is not yet on 36 I updated it to the latest version and py36. See https://github.com/conda-forge/oauthlib-feedstock/pull/5. Once that PR gets accepted this should also run on py36.

**Comment by nikicc** [comment]
I still cannot find py36 build of 0.7.0 with conda. Could it be that this got merged too quickly, before the py36 oauthlib got available on conda? If so, @pmlandwehr any ideas how to re-trigger the building process to also build py36?

**Comment by pmlandwehr** [comment]
Yeah - still not positive what's up here  and we're getting beyond me. I've gone ahead and submitted a new build that adjusts the template a bit (needed to be brought up to date) and rebuilds again. Other thoughts, @ocefpaf ?

**Comment by nikicc** [comment]
Great, that seems to start building py36 so I guess all is good.

**Comment by ocefpaf** [comment]
> Other thoughts, @ocefpaf ?

I am a bit lost in the issue, but I guess it is all sorted, right? If not feel free to ping me again.

**Pull request merged**
